"""Create base models for application.

Revision ID: b4509877eacc
Revises: 
Create Date: 2020-09-26 16:02:38.858090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4509877eacc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('emails',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('personal', 'work', name='contacttype'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('phones',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('personal', 'work', name='contacttype'), nullable=False),
    sa.Column('country_code', sa.String(length=7), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('extension', sa.String(length=7), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('posts',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('phones')
    op.drop_table('emails')
    op.drop_table('users')
    # ### end Alembic commands ###
